name: quran_khani
description: A Quran Khani mobile application

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # State Management
  provider: ^6.1.1

  # Networking
  http: ^1.1.0

  # Google Sign In
  google_sign_in: ^6.2.1

  # Storage
  shared_preferences: ^2.2.2

  # UI Components
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
